/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package graphai

import kotlin.test.Test
import kotlin.test.assertTrue

class GraphAITest {
    @Test
    fun testSanityCheck() {
        assertTrue(true)
    }
}
